CREATE DATABASE IF NOT EXISTS videos;

USE videos;

CREATE TABLE IF NOT EXISTS favorites (
    id CHAR(36) NOT NULL PRIMARY KEY,
    videoId VARCHAR(50) NOT NULL UNIQUE,
    title VARCHAR(255) NOT NULL,
    thumbnail VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TRIGGER before_insert_favorites
    BEFORE INSERT ON favorites
    FOR EACH ROW
    SET NEW.id = UUID();